// Ready-made patterns. Each row is one row of cells: '.' is empty, every other letter
// is a key into `palette`. Edit the rows directly; the gallery, the PNG download and
// the bead pattern all come from them.
//
// Clawd is Anthropic's Claude Code mascot. These are fan-made pixel versions, drawn
// to fit one 29 x 29 pegboard each. Colours are MARD beads, except the body, which
// is Claude orange (#d97757) and lands on MARD F23.
window.BEAD_PRESETS = {
  palette: {
    b: '#50a9f0', // C6
    c: '#9d5b3e', // G7
    d: '#474747', // H5
    g: '#fdad49', // A6
    k: '#2c2c2c', // H6
    l: '#cecdd5', // H11
    m: '#868686', // H4
    n: '#7cee9d', // B3
    o: '#d97757', // Claude orange → F23
    p: '#ffa9ad', // F14
    r: '#e54b4f', // F25
    w: '#ffffff', // H2
  },
  collections: [
    {
      id: 'clawd',
      name: 'Clawd',
      items: [
        { id: 'clawd-classic', name: '经典', rows: [
          '...oooooooooooooo...',
          '...oooooooooooooo...',
          '...oookkooookkooo...',
          'ooooookkooookkoooooo',
          'oooooooooooooooooooo',
          '...oooooooooooooo...',
          '...oooooooooooooo...',
          '...oooooooooooooo...',
          '...oo.oo....oo.oo...',
          '...oo.oo....oo.oo...',
          '...oo.oo....oo.oo...',
        ] },
        { id: 'clawd-hello', name: '你好', rows: [
          '.......................l',
          '......................l.',
          '...................oo...',
          '...................oo.l.',
          '...oooooooooooooo..oo..l',
          '...oooooooooooooo..oo...',
          '...oookkooookkooo..oo...',
          'oooookookookookoooooo...',
          'ooooooooooooooooooooo...',
          '...oppooooooooppo.......',
          '...oooooooooooooo.......',
          '...oooooooooooooo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
        ] },
        { id: 'clawd-coding', name: '写代码', rows: [
          '.....................g..',
          '....................ggg.',
          '...oooooooooooooo..ggggg',
          '...oooooooooooooo...ggg.',
          '...oookkooookkooo....g..',
          'ooooookkooookkoooooo....',
          'oooooooooooooooooooo....',
          '..ddddddddddddddddd.....',
          '..dkkkkkkkkkkkkkkkd.....',
          '..dkkknkkkknkknkkkd.....',
          '..dkknkkkkknkkknkkd.....',
          '..dknkkkkknkkkkknkd.....',
          '..dkknkkknkkkkknkkd.....',
          '..dkkknkknkkkknkkkd.....',
          '..dkkkkkkkkkkkkkkkd.....',
          '..ddddddddddddddddd.....',
          'mmmmmmmmmmmmmmmmmmmmm...',
          'mmmmmmmmmmmmmmmmmmmmm...',
        ] },
        { id: 'clawd-thinking', name: '思考中', rows: [
          '....................o...',
          '..................o.o.o.',
          '...................ooo..',
          '...............m.ooooooo',
          '...................ooo..',
          '.............m....o.o.o.',
          '....................o...',
          '...oooooooooooooo.......',
          '...ooookkooookkoo.......',
          '...ooookkooookkoo.......',
          'oooooooooooooooooooo....',
          'oooooooooooooooooooo....',
          '...oooooooooooooo.......',
          '...oooooooooooooo.......',
          '...oooooooooooooo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
        ] },
        { id: 'clawd-music', name: '听歌', rows: [
          '.....................kkkk.',
          '.....................k..k.',
          '.....dddddddddd......k..k.',
          '...dd..........dd...kk.kk.',
          '..d..............d..kk.kk.',
          '..d..............d........',
          '..dooooooooooooood.....k..',
          'dddooooooooooooooddd...kk.',
          'dmdookookookookoodmd...k.k',
          'dmdoookkooookkooodmd..kk..',
          'dmdoooooooooooooodmd..kk..',
          'dddooooooooooooooddd......',
          '...oooooooooooooo.........',
          '...oooooooooooooo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
        ] },
        { id: 'clawd-love', name: '喜欢', rows: [
          '..................rr.rr.',
          '..................rrrrr.',
          '..............r.r..rrr..',
          '..............rrr...r...',
          '...............r........',
          '.....................r.r',
          '...oooooooooooooo....rrr',
          '...oooooooooooooo.....r.',
          '...oororoooororoo.......',
          'ooooorrroooorrrooooo....',
          'oooooorooooooroooooo....',
          '...oooooooooooooo.......',
          '...oooooooooooooo.......',
          '...oooooooooooooo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
          '...oo.oo....oo.oo.......',
        ] },
        { id: 'clawd-sleepy', name: '晚安', rows: [
          '.....................bbbbb',
          '.............bbbbww.....b.',
          '............bbbbbww....b..',
          '.......bbbbb..........b...',
          '......bbbbbbbb.......bbbbb',
          '.....bbbbbbbbbb...........',
          '....bbbbbbbbbbb....bbb....',
          '...wwwwwwwwwwwwww....b....',
          '...oooooooooooooo...b.....',
          '...oooooooooooooo..bbb....',
          '...ookookookookoo.........',
          'ooooookkooookkoooooo......',
          'oooooooooooooooooooo......',
          '...oooooooooooooo.........',
          '...oooooooooooooo.........',
          '...oooooooooooooo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
        ] },
        { id: 'clawd-coffee', name: '咖啡时间', rows: [
          '.....................l..l.',
          '......................l..l',
          '.....................l..l.',
          '....................mmmmmm',
          '...oooooooooooooo...mccccm',
          '...oooooooooooooo...mwwwwm',
          '...oookkooookkooo...mwowwm',
          'oooookookookookooooomwwwwm',
          'oooooooooooooooooooomwwwwm',
          '...oppooooooooppo....mmmm.',
          '...oooooooooooooo.........',
          '...oooooooooooooo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
          '...oo.oo....oo.oo.........',
        ] },
      ],
    },
  ],
};
